>>>
testCase._error(
    'Callback ${id}called ($actualCalls) after test case '
    '${testCase.description} has already been marked as '
    '${testCase.result}.$reason');
<<<
testCase._error(
  'Callback ${id}called ($actualCalls) after test case '
  '${testCase.description} has already been marked as '
  '${testCase.result}.$reason',
);